name: Create GitHub release

on:
  workflow_dispatch:
    inputs:
      release:
        type: choice
        description: 'Should this build be released?'
        options:
        - true
        - false
        default: 'false'
      ref_to_build:
        description: 'Ref to build (only tested by providing tags), e.g. v6.1.0'
        required: true

env:
  SIGNAL_TAG: ${{ inputs.ref_to_build }}

jobs:
  release:
    runs-on: ubuntu-latest
    if: inputs.release == 'true'

    outputs:
      release_url: ${{ steps.release-url.outputs.html_url }}
      signal_version: ${{ steps.signal-version.outputs.version }}

    steps:
    - name: Get GH token
      id: generate_token
      uses: tibdex/github-app-token@v2
      with:
        app_id: ${{ secrets.GH_APP_DENNIS_APP_ID }}
        private_key: ${{ secrets.GH_APP_DENNIS_PRIVATE_KEY }}
    # Turns v6.1.0 into 6.1.0
    - name: Get version from tag
      id: signal-version
      run: |
        SIGNAL_VERSION=${SIGNAL_TAG#"v"}
        echo "SIGNAL_VERSION=${SIGNAL_VERSION}" >> $GITHUB_ENV
        echo "SIGNAL_TAG=${SIGNAL_TAG}" >> $GITHUB_ENV
        echo "::set-output name=version::${SIGNAL_VERSION}"
    - uses: ncipollo/release-action@v1
      id: release-url
      with:
        owner: dennisameling
        repo: Signal-Desktop
        tag: ${{ inputs.ref_to_build }}
        body: |
          This is the v${{ env.SIGNAL_VERSION }} release.

          ## Linux arm64

          This release contains a `.deb` file for Linux users. Note that auto-updates are **not** supported on this platform.

          ## Windows arm64

          > [!WARNING]  
          > Official support for Windows arm64 [was added in Signal 7.34.0](https://github.com/signalapp/Signal-Desktop/issues/3745#issuecomment-2489355026), meaning that I will no longer be offering builds for Signal Unofficial. The last release with Windows arm64 support here is 7.35.0. **You can migrate to the official client while keeping all your chat history and data**. Instructions are [here](https://github.com/dennisameling/Signal-Desktop/issues/24#issuecomment-2490816224).
        name: v${{ env.SIGNAL_VERSION }}
        token: ${{ steps.generate_token.outputs.token }}
    - uses: actions/github-script@v7.0.1
      name: Trigger CircleCI build + publish
      env:
        CIRCLECI_API_TOKEN: ${{ secrets.CIRCLECI_API_TOKEN }}
        GITHUB_RELEASE_UPLOAD_URL: ${{ steps.release-url.outputs.upload_url }}
      with:
        script: |
          await fetch('https://circleci.com/api/v2/project/gh/dennisameling/signal-desktop-automation/pipeline', {
            method: 'post',
            body: JSON.stringify({
              branch: 'main',
              parameters: {
                ref_to_build: process.env.SIGNAL_TAG,
                github_actions_release_upload_url: process.env.GITHUB_RELEASE_UPLOAD_URL
              }
            }),
            headers: {
              'Circle-Token': process.env.CIRCLECI_API_TOKEN,
              'Content-Type': 'application/json'
            }
          });

          console.log(`Successfully started CircleCI pipeline. It'll add the generated binary to the GitHub release when it's done.`)
